name: Dummy SARIF Upload for Setup

on:
  push:
    branches: [ "main" ]  # Trigger on push to main branch
  workflow_dispatch:   # Allows manual trigger

jobs:
  dummy_sarif_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Permissions to read and write contents
      security-events: write # Permissions to post security events (this is crucial for SARIF uploads)
      actions: read        # Permissions for reading actions data

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      # 🧪 Generate dummy SARIF file
      - name: Generate Dummy SARIF
        run: |
          mkdir -p ./scan-results
          echo '{"version":"2.1.0","runs":[{"tool":{"driver":{"name":"FakeScanner","rules":[]}},"results":[]}]}'> ./scan-results/dummy.sarif

      # ☁️ Upload the Dummy SARIF to GitHub
      - name: Upload Dummy SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./scan-results/dummy.sarif
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-processing: true
